trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  imageName: 'ticketingdemo'

steps:
- task: Docker@2
  displayName: Build Docker image
  inputs:
    command: build
    dockerfile: Web/Dockerfile
    buildContext: .
    tags: |
      $(Build.BuildId)
